# Generated by Django 2.0.1 on 2018-01-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('bio', models.TextField()),
                ('facebook_link', models.TextField()),
                ('twitter_link', models.TextField()),
                ('linkedin_link', models.TextField()),
                ('photo', models.ImageField(upload_to='speakers')),
                ('panel', models.ManyToManyField(to='agenda.Panel')),
            ],
        ),
    ]
