# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0025_speaker_og_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
    ]
