# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-23 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0026_speaker_moderator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ['-moderator']},
        ),
    ]
