# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20180130_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='roundtable',
            field=models.BooleanField(default=False),
        ),
    ]
