# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_remove_sponsor_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ('category',)},
        ),
    ]
